version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: ecommerce_frontend
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_BACKEND_HOSTNAME=${NEXT_PUBLIC_BACKEND_HOSTNAME}
      - NEXTAUTH_URL=${NEXTAUTH_URL}

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    container_name: ecommerce_nginx
    depends_on:
      - frontend
